
experiment_name: "FWI-2025-Nov07-bui-idealized"
path_to_experiments: "/home/rpayne/data-rpayne/trained-models/sf8/"
path_to_zarr: "/home/rpayne/data-rpayne/proc/WRF-USASK/cint/" # path in which the .zarr files are stored
path_to_output: "/sapho/rpayne/mlanalysis/output/" # path in which to store output figures
output_fig_format: "png"
output_fig_dpi: 150
split: "test" # options: "train", "validation", "test"
seed: 242
which_gpu: 0
subset_idxs:
  - 2880
  - 5856
covariate_names:
  - "tas"
  - "uas"
  - "vas"
  - "psfc"
  - "q2"
  - "pr"
  - "bui"
predictand_names:
  - "bui"